Repository choderalab/modelforge, pull requests merged in 2024-07, with the labels that each got.

#185 remove torchani dependencies
  .gitignore
  devtools/conda-envs/doc_env.yaml
  devtools/conda-envs/test_env.yaml
  devtools/conda-envs/test_env_mac.yaml
  docs/training.rst
  modelforge/tests/precalculated_values.py
  modelforge/tests/test_ani.py
Labels: refactoring

#171 Refactor radial basis functions
  modelforge/potential/__init__.py
  modelforge/potential/ani.py
  modelforge/potential/painn.py
  modelforge/potential/physnet.py
  modelforge/potential/sake.py
  modelforge/potential/schnet.py
  modelforge/potential/utils.py
  modelforge/tests/conftest.py
  modelforge/tests/test_ani.py
  modelforge/tests/test_nn.py
  modelforge/tests/test_physnet.py
  modelforge/tests/test_sake.py
  modelforge/tests/test_schnet.py
  modelforge/tests/test_spk.py
  modelforge/tests/test_utils.py
Labels: refactoring

#196 Remove pyg dependency
  devtools/conda-envs/doc_env.yaml
  devtools/conda-envs/test_env.yaml
  devtools/conda-envs/test_env_mac.yaml
  modelforge/dataset/utils.py
  modelforge/potential/ani.py
  modelforge/potential/models.py
  modelforge/potential/painn.py
  modelforge/potential/physnet.py
  modelforge/potential/schnet.py
  modelforge/potential/utils.py
  modelforge/tests/data/training_defaults/default.toml
  modelforge/tests/test_painn.py
  modelforge/tests/test_training.py
  modelforge/tests/test_utils.py
  modelforge/train/training.py
Labels: refactoring, optimization

#194 Ref postprocessing and loss
  devtools/conda-envs/doc_env.yaml
  devtools/conda-envs/test_env.yaml
  devtools/conda-envs/test_env_mac.yaml
  modelforge/dataset/dataset.py
  modelforge/dataset/utils.py
  modelforge/potential/ani.py
  modelforge/potential/models.py
  modelforge/potential/painn.py
  modelforge/potential/physnet.py
  modelforge/potential/processing.py
  modelforge/potential/sake.py
  modelforge/potential/schnet.py
  modelforge/potential/utils.py
  modelforge/tests/conftest.py
  modelforge/tests/data/potential_defaults/ani2x.toml
  modelforge/tests/data/potential_defaults/ani2x_without_ase.toml
  modelforge/tests/data/potential_defaults/painn.toml
  modelforge/tests/data/potential_defaults/painn_without_ase.toml
  modelforge/tests/data/potential_defaults/physnet.toml
  modelforge/tests/data/potential_defaults/physnet_without_ase.toml
  modelforge/tests/data/potential_defaults/sake.toml
  modelforge/tests/data/potential_defaults/sake_without_ase.toml
  modelforge/tests/data/potential_defaults/schnet.toml
  modelforge/tests/data/potential_defaults/schnet_without_ase.toml
  modelforge/tests/data/training/default.toml
  modelforge/tests/data/training_defaults/default.toml
  modelforge/tests/test_ani.py
  modelforge/tests/test_dataset.py
  modelforge/tests/test_models.py
  modelforge/tests/test_painn.py
  modelforge/tests/test_physnet.py
  modelforge/tests/test_sake.py
  modelforge/tests/test_schnet.py
  modelforge/tests/test_spk.py
  modelforge/tests/test_training.py
  modelforge/tests/test_utils.py
  modelforge/train/training.py
Labels: refactoring

#202 Moving call to input preparation to BaseNetwork
  modelforge/potential/ani.py
  modelforge/potential/models.py
  modelforge/potential/painn.py
  modelforge/potential/physnet.py
  modelforge/potential/sake.py
  modelforge/potential/schnet.py
Labels: refactoring

#203 fix inconsistency in weight/bias initialization
  modelforge/potential/utils.py
Labels: bug

#199 Add wandb logger
  modelforge/dataset/utils.py
  modelforge/potential/models.py
  modelforge/potential/schnet.py
  modelforge/tests/data/runtime_defaults/runtime.toml
  modelforge/tests/data/training_defaults/default.toml
  modelforge/tests/test_models.py
  modelforge/tests/test_training.py
  modelforge/train/training.py
  scripts/config.toml
  scripts/profile_network.py
  scripts/toml_examples/ani2x_phalkethoh.toml
  scripts/toml_examples/ani2x_qm9.toml
  scripts/toml_examples/painn_qm9.toml
  scripts/toml_examples/physnet_qm9.toml
  scripts/toml_examples/sake_qm9.toml
  scripts/toml_examples/schnet_qm9.toml
  scripts/training_run.sh
  scripts/training_testing.py
Labels: enhancement

#192 Add nondimensionalizing scale factor to SAKE
  modelforge/potential/sake.py
  modelforge/tests/test_sake.py
Labels: enhancement

#204 allow additional features in embedding
  modelforge/dataset/dataset.py
  modelforge/potential/ani.py
  modelforge/potential/models.py
  modelforge/potential/painn.py
  modelforge/potential/physnet.py
  modelforge/potential/sake.py
  modelforge/potential/schnet.py
  modelforge/potential/tensornet.py
  modelforge/potential/utils.py
  modelforge/tests/data/potential_defaults/painn.toml
  modelforge/tests/data/potential_defaults/physnet.toml
  modelforge/tests/data/potential_defaults/sake.toml
  modelforge/tests/data/potential_defaults/schnet.toml
  modelforge/tests/test_ani.py
  modelforge/tests/test_dataset.py
  modelforge/tests/test_nn.py
  modelforge/tests/test_painn.py
  modelforge/tests/test_sake.py
  modelforge/tests/test_schnet.py
  modelforge/tests/test_spk.py
  modelforge/train/training.py
Labels: enhancement

#206 Major refactoring to use pydantic models for config files.
  devtools/conda-envs/test_env.yaml
  devtools/conda-envs/test_env_mac.yaml
  modelforge/dataset/dataset.py
  modelforge/dataset/utils.py
  modelforge/potential/__init__.py
  modelforge/potential/ani.py
  modelforge/potential/models.py
  modelforge/potential/painn.py
  modelforge/potential/parameters.py
  modelforge/potential/physnet.py
  modelforge/potential/sake.py
  modelforge/potential/schnet.py
  modelforge/tests/data/dataset_defaults/ani1x.toml
  modelforge/tests/data/dataset_defaults/ani2x.toml
  modelforge/tests/data/dataset_defaults/phalkethoh.toml
  modelforge/tests/data/dataset_defaults/qm9.toml
  modelforge/tests/data/dataset_defaults/spice1.toml
  modelforge/tests/data/dataset_defaults/spice1_openff.toml
  modelforge/tests/data/dataset_defaults/spice2.toml
  modelforge/tests/data/potential_defaults/ani2x.toml
  modelforge/tests/data/potential_defaults/painn.toml
  modelforge/tests/data/potential_defaults/physnet.toml
  modelforge/tests/data/potential_defaults/sake.toml
  modelforge/tests/data/potential_defaults/schnet.toml
  modelforge/tests/data/runtime_defaults/runtime.toml
  modelforge/tests/data/training_defaults/default.toml
  modelforge/tests/test_ani.py
  modelforge/tests/test_curation.py
  modelforge/tests/test_dataset.py
  modelforge/tests/test_models.py
  modelforge/tests/test_nn.py
  modelforge/tests/test_painn.py
  modelforge/tests/test_parameter_models.py
  modelforge/tests/test_physnet.py
  modelforge/tests/test_sake.py
  modelforge/tests/test_schnet.py
  modelforge/tests/test_training.py
  modelforge/tests/test_utils.py
  modelforge/train/parameters.py
  modelforge/train/training.py
  modelforge/utils/misc.py
  modelforge/utils/units.py
  scripts/config.toml
  scripts/profile_epoch.py
  scripts/profile_network.py
Labels: enhancement
