Repository choderalab/modelforge, pull requests merged in 2024-04, with the labels that each got.

#88 Split NNPs in inference and training models
  modelforge/dataset/__init__.py
  modelforge/dataset/dataset.py
  modelforge/potential/__init__.py
  modelforge/potential/models.py
  modelforge/tests/conftest.py
  modelforge/tests/helper_functions.py
  modelforge/tests/test_dataset.py
  modelforge/tests/test_models.py
  modelforge/tests/test_painn.py
  modelforge/tests/test_schnet.py
  modelforge/tests/test_training.py
  scripts/training.py
Labels: refactoring

#93 Include forces in loss function
  modelforge/potential/ani.py
  modelforge/potential/models.py
  modelforge/potential/painn.py
  modelforge/potential/physnet.py
  modelforge/potential/physnet.rst
  modelforge/potential/postprocessing.py
  modelforge/potential/schnet.py
  modelforge/potential/utils.py
  modelforge/tests/test_ani.py
  modelforge/train/training.py
  modelforge/train/tuning.py
Labels: enhancement

#90 ray tuning
  .github/workflows/CI.yaml
  devtools/conda-envs/test_env.yaml
  modelforge/dataset/utils.py
  modelforge/potential/ani.py
  modelforge/potential/models.py
  modelforge/potential/painn.py
  modelforge/potential/physnet.py
  modelforge/potential/physnet.rst
  modelforge/potential/postprocessing.py
  modelforge/potential/schnet.py
  modelforge/potential/utils.py
  modelforge/tests/test_ani.py
  modelforge/tests/test_models.py
  modelforge/tests/test_training.py
  modelforge/train/training.py
  modelforge/train/tuning.py
  modelforge/train/utils.py
  scripts/tuning.py
Labels: enhancement

#97 removed elements not implemented from ATOMIC_NUMBER_TO_INDEX_MAP
  modelforge/dataset/dataset.py
  modelforge/potential/ani.py
  modelforge/potential/utils.py
  modelforge/tests/test_dataset.py
Labels: bug
