Repository choderalab/modelforge, pull requests merged in 2024-10, with the labels that each got.

#261 Update pr template
  .codecov.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/CI.yaml
  docs/for_developer.rst
Labels: enhancement

#268 Optimize the training routine
  modelforge/potential/models.py
  modelforge/tests/data/training_defaults/default.toml
  modelforge/tests/data/training_defaults/default_with_force.toml
  modelforge/tests/data/training_defaults/train_with_dipole_moment.toml
  modelforge/tests/test_training.py
  modelforge/train/losses.py
  modelforge/train/parameters.py
  modelforge/train/training.py
  scripts/config.toml
Labels: refactoring

#254 add dipole moment loss
  devtools/conda-envs/test_env.yaml
  devtools/conda-envs/test_env_mac.yaml
  modelforge/curation/phalkethoh_curation.py
  modelforge/curation/scripts/curate_spice114.py
  modelforge/curation/scripts/curate_spice114_openff.py
  modelforge/curation/scripts/curate_spice2.py
  modelforge/curation/spice_1_curation.py
  modelforge/curation/spice_1_openff_curation.py
  modelforge/curation/spice_2_curation.py
  modelforge/custom_types.py
  modelforge/dataset/ani2x.py
  modelforge/dataset/dataset.py
  modelforge/dataset/qm9.py
  modelforge/dataset/spice1.py
  modelforge/dataset/spice2.py
  modelforge/dataset/yaml_files/spice1.yaml
  modelforge/dataset/yaml_files/spice1openff.yaml
  modelforge/dataset/yaml_files/spice2.yaml
  modelforge/potential/aimnet2.py
  modelforge/potential/models.py
  modelforge/potential/parameters.py
  modelforge/potential/processing.py
  modelforge/potential/sake.py
  modelforge/tests/conftest.py
  modelforge/tests/data/config.toml
  modelforge/tests/data/potential_defaults/schnet.toml
  modelforge/tests/data/runtime_defaults/runtime.toml
  modelforge/tests/data/training_defaults/default.toml
  modelforge/tests/data/training_defaults/default_with_force.toml
  modelforge/tests/helper_functions.py
  modelforge/tests/test_dataset.py
  modelforge/tests/test_models.py
  modelforge/tests/test_training.py
  modelforge/tests/test_utils.py
  modelforge/train/losses.py
  modelforge/train/parameters.py
  modelforge/train/training.py
  modelforge/utils/prop.py
  scripts/config.toml
Labels: enhancement

#270 Set value to monitor during training in single place
  docs/getting_started.rst
  modelforge/tests/data/config.toml
  modelforge/tests/data/training_defaults/default.toml
  modelforge/tests/test_training.py
  modelforge/train/parameters.py
  modelforge/train/training.py
  scripts/config.toml
Labels: enhancement

#280 add correct placeholder variable name
  modelforge/train/training.py
Labels: bug

#285 Add convenience function to generate inference model from training checkpoint file
  docs/inference.rst
  modelforge/potential/models.py
  modelforge/tests/data/best_SchNet-PhAlkEthOH-epoch=00.ckpt
  modelforge/tests/test_models.py
Labels: enhancement

#283 Rename variable names in NNP factory class
  docs/index.rst
  docs/potentials.rst
  docs/training.rst
  modelforge/dataset/dataset.py
  modelforge/potential/__init__.py
  modelforge/potential/potential.py
  modelforge/tests/helper_functions.py
  modelforge/tests/precalculated_values.py
  modelforge/tests/test_aimnet2.py
  modelforge/tests/test_ani.py
  modelforge/tests/test_dataset.py
  modelforge/tests/test_nn.py
  modelforge/tests/test_painn.py
  modelforge/tests/test_potentials.py
  modelforge/tests/test_sake.py
  modelforge/tests/test_schnet.py
  modelforge/tests/test_tensornet.py
  modelforge/tests/test_training.py
  modelforge/train/training.py
  modelforge/utils/vis.py
Labels: refactoring

#287 Change input data structure from named tuple to a class with slots
  docs/datasets.rst
  docs/getting_started.rst
  docs/potentials.rst
  docs/training.rst
  modelforge/dataset/__init__.py
  modelforge/dataset/dataset.py
  modelforge/dataset/utils.py
  modelforge/jax.py
  modelforge/potential/aimnet2.py
  modelforge/potential/ani.py
  modelforge/potential/featurization.py
  modelforge/potential/neighbors.py
  modelforge/potential/painn.py
  modelforge/potential/parameters.py
  modelforge/potential/physnet.py
  modelforge/potential/potential.py
  modelforge/potential/processing.py
  modelforge/potential/sake.py
  modelforge/potential/schnet.py
  modelforge/potential/tensornet.py
  modelforge/potential/utils.py
  modelforge/tests/conftest.py
  modelforge/tests/data/best_SchNet-PhAlkEthOH-epoch=00.ckpt
  modelforge/tests/data/config.toml
  modelforge/tests/data/conv.ipynb
  modelforge/tests/data/nnp_input.pkl
  modelforge/tests/data/positions.pt
  modelforge/tests/data/potential_defaults/aimnet2.toml
  modelforge/tests/data/potential_defaults/ani2x.toml
  modelforge/tests/data/potential_defaults/painn.toml
  modelforge/tests/data/potential_defaults/physnet.toml
  modelforge/tests/data/potential_defaults/sake.toml
  modelforge/tests/data/potential_defaults/schnet.toml
  modelforge/tests/data/potential_defaults/tensornet.toml
  modelforge/tests/data/training_defaults/default.toml
  modelforge/tests/precalculated_values.py
  modelforge/tests/test_aimnet2.py
  modelforge/tests/test_ani.py
  modelforge/tests/test_dataset.py
  modelforge/tests/test_nn.py
  modelforge/tests/test_painn.py
  modelforge/tests/test_pairlist.py
  modelforge/tests/test_parameter_models.py
  modelforge/tests/test_physnet.py
  modelforge/tests/test_potentials.py
  modelforge/tests/test_sake.py
  modelforge/tests/test_schnet.py
  modelforge/tests/test_spk.py
  modelforge/tests/test_tensornet.py
  modelforge/tests/test_training.py
  modelforge/train/losses.py
  modelforge/train/training.py
  modelforge/train/tuning.py
  modelforge/utils/prop.py
  modelforge/utils/vis.py
  scripts/config.toml
Labels: refactoring

#289 Log the gradient norm of loss component and model parameters
  modelforge/train/parameters.py
  modelforge/train/training.py
Labels: enhancement

#288 Separate training and inference from NNP factory
  docs/potentials.rst
  modelforge/potential/potential.py
  modelforge/tests/helper_functions.py
  modelforge/tests/test_painn.py
  modelforge/tests/test_potentials.py
  modelforge/tests/test_schnet.py
  modelforge/tests/test_training.py
  modelforge/train/training.py
Labels: enhancement

#296 Adding additional learning rate scheduler
  modelforge/potential/parameters.py
  modelforge/tests/data/best_SchNet-PhAlkEthOH-epoch=00.ckpt
  modelforge/tests/data/config.toml
  modelforge/tests/data/training_defaults/default.toml
  modelforge/tests/test_training.py
  modelforge/train/losses.py
  modelforge/train/parameters.py
  modelforge/train/training.py
  scripts/config.toml
Labels: enhancement
