Repository choderalab/modelforge, pull requests merged in 2024-06, with the labels that each got.

#136 Refactoring of PhysNet
  modelforge/potential/physnet.py
Labels: bug

#139 logging weights/biases/parameter histograms for each layer
  modelforge/tests/test_training.py
  modelforge/train/training.py
Labels: enhancement

#142 Profiling scripts for training/inference
  modelforge/potential/processing.py
  notebooks/benchmark.ipynb
  scripts/profile_epoch.py
  scripts/profile_network.py
Labels: enhancement

#144 Remove unused cutoff parameter
  modelforge/potential/ani.py
  modelforge/potential/models.py
  modelforge/potential/painn.py
  modelforge/potential/physnet.py
  modelforge/potential/sake.py
  modelforge/potential/schnet.py
  modelforge/potential/tensornet.py
Labels: refactoring

#146 Splitting pairlist and neighborlist calculation
  .github/workflows/CI.yaml
  modelforge/dataset/dataset.py
  modelforge/potential/models.py
  modelforge/potential/processing.py
  modelforge/potential/utils.py
  modelforge/tests/conftest.py
  modelforge/tests/test_ani.py
  modelforge/tests/test_dataset.py
  modelforge/tests/test_dataset_downloads.py
  modelforge/tests/test_models.py
  modelforge/tests/test_painn.py
  modelforge/tests/test_physnet.py
  modelforge/tests/test_sake.py
  modelforge/tests/test_schnet.py
  modelforge/tests/test_training.py
  setup.py
Labels: enhancement

#137 Training options and control parameters moved to toml files
  .github/workflows/CI.yaml
  modelforge/dataset/dataset.py
  modelforge/potential/ani.py
  modelforge/potential/models.py
  modelforge/potential/painn.py
  modelforge/potential/physnet.py
  modelforge/potential/processing.py
  modelforge/potential/sake.py
  modelforge/potential/schnet.py
  modelforge/potential/utils.py
  modelforge/tests/conftest.py
  modelforge/tests/data/potential_defaults/ani2x_defaults.toml
  modelforge/tests/data/potential_defaults/painn_defaults.toml
  modelforge/tests/data/potential_defaults/physnet_defaults.toml
  modelforge/tests/data/potential_defaults/sake_defaults.toml
  modelforge/tests/data/potential_defaults/schnet_defaults.toml
  modelforge/tests/data/training_defaults/ani2x_ani2x.toml
  modelforge/tests/data/training_defaults/ani2x_qm9.toml
  modelforge/tests/data/training_defaults/painn_ani2x.toml
  modelforge/tests/data/training_defaults/painn_qm9.toml
  modelforge/tests/data/training_defaults/physnet_ani2x.toml
  modelforge/tests/data/training_defaults/physnet_qm9.toml
  modelforge/tests/data/training_defaults/sake_ani2x.toml
  modelforge/tests/data/training_defaults/sake_qm9.toml
  modelforge/tests/data/training_defaults/schnet_ani1x.toml
  modelforge/tests/data/training_defaults/schnet_ani2x.toml
  modelforge/tests/data/training_defaults/schnet_phalkethoh.toml
  modelforge/tests/data/training_defaults/schnet_qm9.toml
  modelforge/tests/data/training_defaults/schnet_spice114.toml
  modelforge/tests/data/training_defaults/schnet_spice114_openff.toml
  modelforge/tests/data/training_defaults/schnet_spice2.toml
  modelforge/tests/test_ani.py
  modelforge/tests/test_dataset.py
  modelforge/tests/test_dataset_downloads.py
  modelforge/tests/test_models.py
  modelforge/tests/test_painn.py
  modelforge/tests/test_physnet.py
  modelforge/tests/test_sake.py
  modelforge/tests/test_schnet.py
  modelforge/tests/test_spk.py
  modelforge/tests/test_training.py
  modelforge/train/training.py
  modelforge/utils/units.py
  notebooks/benchmark.ipynb
  scripts/config.toml
  scripts/perform_training.py
  scripts/profile_epoch.py
  scripts/profile_network.py
  scripts/toml_examples/ani2x_qm9.toml
  scripts/toml_examples/painn_qm9.toml
  scripts/toml_examples/physnet_qm9.toml
  scripts/toml_examples/sake_qm9.toml
  scripts/toml_examples/schnet_qm9.toml
  setup.py
Labels: enhancement

#150 Refactor pairlist representation
  modelforge/dataset/dataset.py
  modelforge/potential/processing.py
  modelforge/tests/test_dataset.py
  modelforge/tests/test_models.py
Labels: enhancement

#152 Ref ani neighborlist
  modelforge/dataset/dataset.py
  modelforge/potential/models.py
  modelforge/tests/test_dataset.py
Labels: bug

#154 Resolve merge conflicts from main and PR #138
  modelforge/dataset/dataset.py
  modelforge/potential/ani.py
  modelforge/potential/models.py
  modelforge/potential/painn.py
  modelforge/potential/physnet.py
  modelforge/potential/sake.py
  modelforge/potential/schnet.py
  modelforge/potential/tensornet.py
  modelforge/potential/utils.py
  modelforge/tests/conftest.py
  modelforge/tests/test_ani.py
  modelforge/tests/test_dataset.py
  modelforge/tests/test_spk.py
  modelforge/train/training.py
Labels: enhancement

#157 Training script accepts multiple config files
  modelforge/train/training.py
Labels: enhancement

#160 Log unused parameters at end of training
  modelforge/train/training.py
Labels: enhancement

#162 Bugfix training script
  modelforge/potential/ani.py
  modelforge/tests/test_ani.py
  modelforge/train/training.py
Labels: bug
